# Generated by Django 2.0.2 on 2018-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=100)),
                ('ipic', models.CharField(max_length=200)),
                ('iprice', models.CharField(max_length=100)),
                ('ides', models.CharField(max_length=900)),
            ],
        ),
    ]
